--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/WavyCraftNetwork/PCEBookShop
build-by-default: true
branches:
- master
projects:
  PCEBookShop:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
...
