name: PCEBookShop
main: Aericio\PCEBookShop\PCEBookShop
version: 1.0.4
api: 5.0.0
author: Aericio
authors: ["WavyCraftNetwork"]#Dont be a smart ass and put your name if you did nothing/barely anything!
depend: [PiggyCustomEnchants]
website: "https://github.com/WavyCraftNetwork/PCEBookShop/"

permissions:
  pcebookshop.command.bookshop:
    default: true
